
function faq(){let accordion=document.querySelector('.faq__accordion');document.querySelector('.accordion-active .faq__answer').style.height=document.querySelector('.accordion-active .faq__answer').scrollHeight+"px";accordion.addEventListener('click',function(){if(event.target.classList.contains('faq__accordion')||event.target.closest('.faq__item').classList.contains('accordion-active')){return;}
if(event.target.classList.contains('faq__question')||event.target.classList.contains("faq__question-text")||event.target.tagName=="IMG"){if(document.querySelector('.accordion-active')!=undefined){document.querySelector('.accordion-active').querySelector('.faq__answer').style.height="0px";document.querySelector('.accordion-active').classList.remove('accordion-active');}
event.target.closest('.faq__item').classList.add('accordion-active');event.target.closest('.faq__item').querySelector('.faq__answer').style.height=event.target.closest('.faq__item').querySelector('.faq__answer').scrollHeight+"px";}})}
function mobileMenuConfiguration(){document.querySelector('.welcome__burgerIcon').addEventListener('click',function(){document.getElementById('background-overlay').classList.add('flex');setTimeout(()=>{document.getElementById('background-overlay').classList.add('opacity-1');})
document.querySelector('.mobileMenu').classList.add('flex');setTimeout(()=>{document.querySelector('.mobileMenu').classList.add('mobileOn');})
console.log("wfewfe");})
document.getElementById('background-overlay').addEventListener('click',closeOverlay);document.querySelector('.mobileMenu__close').addEventListener('click',closeOverlay);document.getElementById('mobileMenu-closeOverlay').addEventListener('click',closeOverlay);function closeOverlay(){document.getElementById('background-overlay').addEventListener('transitionend',localClose);document.getElementById('background-overlay').classList.remove('opacity-1');document.querySelector('.mobileMenu').classList.remove('mobileOn');function localClose(){console.log('opa');document.querySelector('.mobileMenu').classList.remove('flex');document.getElementById('background-overlay').classList.remove('flex');document.getElementById('background-overlay').removeEventListener('transitionend',localClose);}}}
function showVideo(){let triggerVideo=document.querySelectorAll('.triggerVideo');triggerVideo.forEach(element=>{element.addEventListener('click',()=>{document.getElementById('video').classList.add('overlay-active');setTimeout(()=>{document.getElementById('video').classList.add('opacity-1');})
let iframe=document.getElementById('iframe-youtube').contentWindow;iframe.postMessage('{"event":"command","func":"playVideo","args":""}','*');})})}
function closeVideo(){let overlay;document.getElementById('video').addEventListener('click',()=>{if(event.target.classList.contains('overlay')||event.target.classList.contains('container')||event.target.classList.contains('overlay__closeButton')){overlay=event.target.closest('.overlay');let iframe=document.getElementById('iframe-youtube').contentWindow;iframe.postMessage('{"event":"command","func":"pauseVideo","args":""}','*');overlay.classList.remove('opacity-1');overlay.addEventListener('transitionend',correctClosing);}})
let correctClosing=()=>{overlay.classList.remove('overlay-active');overlay.removeEventListener('transitionend',correctClosing);}}
function copyDiscord(){document.querySelectorAll('.copyDiscord').forEach(element=>{element.addEventListener('click',localHandler);});function localHandler(){let safeThis=this;let notifyPos=event.target.closest(".copyDiscord").dataset.pos;this.removeEventListener('click',localHandler);navigator.clipboard.writeText('Folsten#7109').then(()=>{let discordNotify=document.querySelector('.discord__notify');if(notifyPos=="bottom"){discordNotify.classList.add('discordNotifyBottom')};discordNotify.classList.add('flex');setTimeout(()=>{discordNotify.classList.add('opacity-1');setTimeout(()=>{discordNotify.classList.remove('opacity-1');setTimeout(()=>{discordNotify.classList.remove('flex');discordNotify.classList.remove('discordNotifyBottom');this.addEventListener('click',localHandler);},500)},1500)},100)})}}
function price(){let selector=document.querySelector('.purchase__long select');let initialPrice=document.querySelector('.purchase__initialPrice');let currentPrice=document.querySelector('.purchase__currentPrice');let buyButton=document.querySelector('.purchase__buy');let pricesAll={1:{initial:1400,current:980,href:"https://yasobe.ru/na/tarkovbot_1month"},2:{initial:1930,current:1350,href:"https://yasobe.ru/na/tarkovbot_2month"},3:{initial:2460,current:1720,href:"https://yasobe.ru/na/tarkovbot_3month"},};console.log(selector);selector.addEventListener('change',()=>{let amount=event.target.value;initialPrice.innerHTML=pricesAll[amount].initial+" рублей";currentPrice.innerHTML=pricesAll[amount].current+" рублей";buyButton.setAttribute('href',pricesAll[amount].href);})}
faq();mobileMenuConfiguration();showVideo();closeVideo();copyDiscord();price();